application:
  base-url: ${BASE_URL:http://localhost:3000}

spring:
  application:
    name: citytrees
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:54321/citytrees}
    username: ${DB_LOGIN:citytrees}
    password: ${DB_PASSWORD:citytrees}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  flyway:
    connect-retries: 5
    connect-retries-interval: 1s

scheduling:
  enabled: true
  user:
    confirmation-email-delay: PT10S
    password-reset-delay: PT10S

security:
  password-salt: ${PASSWORD_SALT:some_salt}
  email-confirmation-salt: ${EMAIL_CONFIRMATION_SALT:some_salt}
  access-token-duration: 30m
  access-token-secret: ${ACCESS_TOKEN_SECRET:some_secret}
  refresh-token-duration: 365d
  refresh-token-secret: ${REFRESH_TOKEN_SECRET:some_other_secret}
  admin-email: ${ADMIN_EMAIL:admin@citytrees.io}
  admin-password: ${ADMIN_PASSWORD:admin@citytrees.io}

email:
  user: ${EMAIL_USER:citytrees}
  sender-email: ${EMAIL_SENDER:citytrees@example.io}
  password: ${EMAIL_PASSWORD:citytrees}
  smtp-properties:
    mail.smtp.host: smtp.zoho.com
    mail.smtp.port: 465
    mail.smtp.auth: true
    mail.smtp.startssl.enable: true
    mail.smtp.socketFactory.port: 465
    mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

file-storage:
  type: ${DB_TYPE:database}

s3:
  access-key: ${S3_ACCESS_KEY:access-key}
  secret-key: ${S3_SECRET_KEY:secret-key}
  region: ${S3_REGION:eu-south-1}
  service-endpoint: ${S3_SERVICE_ENDPOINT:http://localhost:9090/}
  bucket: ${S3_BUCKET:ct_tree_bucket}

geo:
  srid: ${GEO_SRID:4326}
  cluster-distance: ${CLUSTER_DISTANCE:0.001}
