spring:
  application:
    name: citytrees
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:54321/citytrees}
    username: ${DB_LOGIN:citytrees}
    password: ${DB_PASSWORD:citytrees}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  flyway:
    connect-retries: 5
    connect-retries-interval: 1s

security:
  password-salt: ${PASSWORD_SALT:some_salt}
  access-token-duration: 30m
  access-token-secret: ${ACCESS_TOKEN_SECRET:some_secret}
  refresh-token-duration: 365d
  refresh-token-secret: ${REFRESH_TOKEN_SECRET:some_other_secret}
