spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:54321/citytrees}
    username: ${DB_LOGIN:citytrees}
    password: ${DB_PASSWORD:citytrees}

password:
  salt: ${PASSWORD_SALT:some_salt}
